server {
    listen 80;
    server_name www.athrtk.com;
    return 301 https://athrtk.com$request_uri;
}

server {
    listen 80 default_server;
    server_name athrtk.com localhost _;
    root /usr/share/nginx/html;
    index index.html;
    charset utf-8;
    server_tokens off;
    error_page 404 /404.html;
    gzip on;
    gzip_vary on;
    gzip_min_length 1024;
    gzip_types text/css image/svg+xml application/xml;

    add_header X-Content-Type-Options nosniff always;
    add_header Referrer-Policy strict-origin-when-cross-origin always;
    add_header X-Frame-Options DENY always;

    location / {
        try_files $uri $uri/ =404;
    }
    location /en/ {
        error_page 404 /en/404.html;
        try_files $uri $uri/ =404;
    }
    location ~* \.(?:woff2|svg|png)$ {
        expires 7d;
        add_header Cache-Control "public";
        add_header X-Content-Type-Options nosniff always;
        try_files $uri =404;
    }
    location ~* \.css$ {
        expires 5m;
        add_header Cache-Control "public";
        add_header X-Content-Type-Options nosniff always;
        try_files $uri =404;
    }
}
